# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20171115_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(default='info', max_length=200),
            preserve_default=False,
        ),
    ]
